version: "3"
services:
  proxy:
    image: nginx:1.17.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - prism_1
      - prism_2
  prism_1:
    image: stoplight/prism:3
    command: mock --cors -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml
    expose:
      - 4010
  prism_2:
    image: stoplight/prism:3
    command: mock --cors -p 4010 --host 0.0.0.0 https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml
    expose:
      - 4010
