"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NodeTypes;
(function (NodeTypes) {
    NodeTypes["Info"] = "oas2_info";
    NodeTypes["Description"] = "oas2_description";
    NodeTypes["Tags"] = "oas2_tags";
    NodeTypes["Tag"] = "oas2_tag";
    NodeTypes["SecurityDefinitions"] = "oas2_security_definitions";
    NodeTypes["SecurityDefinition"] = "oas2_security_definition";
    NodeTypes["Paths"] = "oas2_paths";
    NodeTypes["Path"] = "oas2_path";
    NodeTypes["PathParameter"] = "oas2_path_parameter";
    NodeTypes["Operation"] = "oas2_operation";
    NodeTypes["OperationParameter"] = "oas2_operation_parameter";
    NodeTypes["OperationResponse"] = "oas2_operation_response";
    NodeTypes["Shared"] = "oas2_shared";
    NodeTypes["SharedParameter"] = "oas2_shared_parameter";
    NodeTypes["SharedResponse"] = "oas2_shared_response";
    NodeTypes["Parameters"] = "oas2_parameters";
    NodeTypes["Parameter"] = "oas2_parameter";
    NodeTypes["Responses"] = "oas2_responses";
    NodeTypes["Models"] = "oas2_models";
    NodeTypes["Model"] = "oas2_model";
    NodeTypes["Schema"] = "oas2_schema";
    NodeTypes["Headers"] = "oas2_headers";
    NodeTypes["Header"] = "oas2_header";
    NodeTypes["Examples"] = "oas2_examples";
    NodeTypes["Example"] = "oas2_example";
})(NodeTypes = exports.NodeTypes || (exports.NodeTypes = {}));
//# sourceMappingURL=types.js.map