export declare enum NodeTypes {
    Info = "oas2_info",
    Description = "oas2_description",
    Tags = "oas2_tags",
    Tag = "oas2_tag",
    SecurityDefinitions = "oas2_security_definitions",
    SecurityDefinition = "oas2_security_definition",
    Paths = "oas2_paths",
    Path = "oas2_path",
    PathParameter = "oas2_path_parameter",
    Operation = "oas2_operation",
    OperationParameter = "oas2_operation_parameter",
    OperationResponse = "oas2_operation_response",
    Shared = "oas2_shared",
    SharedParameter = "oas2_shared_parameter",
    SharedResponse = "oas2_shared_response",
    Parameters = "oas2_parameters",
    Parameter = "oas2_parameter",
    Responses = "oas2_responses",
    Models = "oas2_models",
    Model = "oas2_model",
    Schema = "oas2_schema",
    Headers = "oas2_headers",
    Header = "oas2_header",
    Examples = "oas2_examples",
    Example = "oas2_example"
}
