openapi: 3.0.2
paths:
  /todos:
    get:
      responses:
        200:
          description: ok
          content:
            application/json:
              example: ok
        default:
          description: default response
          content:
            application/json:
              example: test
