openapi: '3.0.1'
paths:
  /endpoint/{val}:
    get:
      parameters:
        - in: path
          name: val
          schema:
            type: string
      responses:
        200:
          description: abc
