name: Check Markdown Links

on:
  pull_request:
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: planetscale/github-action-markdown-link-check@master
